### PR TITLE
apple clone

### PR DESCRIPTION
**Pull request by ignatius22**
THE APPLE PAGE
This is a frontend project which aims at learning how to make html5 and css by cloning the Apple page.
Features Added

Article section
- it has a background image.
- a navigation bar with a search bar
- some texts.

Aside Section.
- has promo images

Footer
- nav with links

### CODE REVIEW

**Comment by trekab** [comment]
# Changes Required!
Hello @ignatius22! You have done an impressive job with the navigation bar. However, there are several changes you need to make to have [your clone](https://rawcdn.githack.com/ignatius22/apple-clone/30b48dc5eac81299f19652b92d7bde50d27ae86c/index.html) look like the [original site](https://web.archive.org/web/20140301004610/http://www.apple.com/).

- [x] Starting with the README file, the screenshot and the live demo link are broken.
- [x] You have [HTML validator](https://validator.w3.org/#validate_by_upload) errors to fix.
- [x] Your navigation bar should be centered to look more like the [original site](https://web.archive.org/web/20140301004610/http://www.apple.com/).
- [x] Other than the footer and the navigation bar, I have noticed that [your clone](https://rawcdn.githack.com/ignatius22/apple-clone/30b48dc5eac81299f19652b92d7bde50d27ae86c/index.html) lacks the remaining features that would make it look like the [original site](https://web.archive.org/web/20140301004610/http://www.apple.com/). Please add all the features that appear on the [original site](https://web.archive.org/web/20140301004610/http://www.apple.com/).

__Kindly work on the requested changes and submit another code review request__
_Feel free to contact me on slack for any inquiries about this review_
__Treasure Kabareebe__

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @ignatius22, you did a great job fixing all the changes recommended by the previous TSE :+1: However, I found a few issues I need you to address before we move on. Kindly find comments below:
- Stickler is not enabled for the repo, kindly fix and address it by visiting stickler-ci.com
- Kindly fix the horizontal scroll
- Kindly avoid using tag names for styling, use only classes and remember to apply the DRY rule. Check [this](https://speckyboy.com/good-bad-css-practices/) out

Kindly make these changes and submit another code review :smile: 
_Happy coding_ :man_technologist: 
Daniel Larbi Addo on slack

**Review by christianotieno — CHANGES_REQUESTED** [review]
## Awesome work @ignatius22  

### [The clone](https://raw.githack.com/ignatius22/apple-clone/awaiting_reviews/index.html) shows good use of CSS Backgrounds and Gradients. :100: 

A few required changes: Note that for this project, we have to make sure nothing is messed up. Please see difference in the source page and the clone below: 

| [Current clone](https://raw.githack.com/ignatius22/apple-clone/awaiting_reviews/index.html) | [Source Page](https://web.archive.org/web/20140301004610/http://www.apple.com/) |
|:-----:|:-----:|
| clone | source|


- FIx the conflict with this branch.

#### :recycle:  Make these changes and submit another code review request. :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Christian Otieno](https://github.com/christianotieno) 

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :airplane: 

Hi @ignatius22, congratulations on fixing all changes recommended by the previous TSE's :+1: On this note, our project now meets all the minimum requirements :smile: 

Go ahead and merge to master and submit the project completion form :+1: 
_Happy coding_ :man_technologist: 
See you at the top :smile: 
Daniel Larbi Addo on slack

**Pull request merged**
